{
 "title": "SRE Metatracker",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Infra Dashboard Control",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_issues_by_label{label=\"Doing\",state=\"opened\"}",
     "legendFormat": "{{ label }}"
    },
    {
     "expr": "gitlab_issues_by_label{label=\"Prioritized Week\",state=\"opened\"}",
     "legendFormat": "{{ label }}"
    },
    {
     "expr": "gitlab_issues_by_label{label=\"Review\",state=\"opened\"}",
     "legendFormat": "{{ label }}"
    },
    {
     "expr": "gitlab_issues_by_label{label=\"Blocked\",state=\"opened\"}",
     "legendFormat": "{{ label }}"
    },
    {
     "expr": "gitlab_issues_by_label{label=\"To Do\",state=\"opened\"}",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  {
   "title": "Big Open tasks by Member",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(gitlab_issues_by_weight{weight=\"8\",state=\"opened\"}) by (assignee)",
     "legendFormat": "{{ assignee }}"
    }
   ]
  },
  {
   "title": "Open issues by priority",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "gitlab_issues_by_label{label=~\"P::.*\",state=\"opened\"}",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  {
   "title": "Total Weight for Opened Tasks by Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_issues_weight_by_assignee{state=\"opened\"}) by (assignee)",
     "legendFormat": "{{ assignee }}"
    }
   ]
  },
  {
   "title": "Infra Core Q3 Open Issues by Milestone",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_issues_by_milestone{milestone=~\"Sprint [0-9]+ - Q[0-9]+ - Core Services\", state=\"opened\"}) by (milestone)",
     "legendFormat": "{{ milestone }}"
    }
   ]
  }
 ]
}